! Hello.f95

MODULE VIPER_FORTRAN_HELLO_MODLUE
   USE, INTRINSIC :: ISO_C_BINDING
   IMPLICIT NONE

CONTAINS
   SUBROUTINE VIPER_FORTRAN_HELLO() BIND(C, NAME="ViperFortranHello")
      WRITE(*,*) "Hello, World!"
   END SUBROUTINE VIPER_FORTRAN_HELLO

END MODULE VIPER_FORTRAN_HELLO_MODLUE
