source/application/application.c File Reference
#include <viper/debug/logger.h>
#include <viper/types.h>
#include <viper/utils/stringer.h>
#include <viper/application/application.h>
#include <viper/opengl/init.h>
#include <viper/vulkan/init.h>
Functions
static void __ViperEmptyLoopNoCall (ViperApplication_t *app)
These function is internal helper functions.
static void __ViperRenderLoopNoCall (ViperApplication_t *app)
static void __ViperApplicationLoop (ViperApplication_t *app)
The main application loop that will call the user space loop.
int ViperApplicationCreate (ViperApplication_t *app, const ViperApplicationCreateInfo_t *info)
This function can either be called directly or using the create function, it will initiliaze the struct using the data provided in the ApplicationCreateInfo_t.
void ViperApplicationStart (ViperApplication_t *app)
Variables
static void(* __ViperRenderLoop)(ViperApplication_t *app) = &__ViperEmptyLoopNoCall
This is local global varible to allows the user to switch between multiple rendering methods.
Function Documentation
__ViperApplicationLoop()
static void __ViperApplicationLoop (ViperApplication_t * app) [static]
The main application loop that will call the user space loop.
Parameters
app :: is the Application_t struct for the program.
Definition at line 36 of file application.c.
References __ViperRenderLoop, __ViperApplication_t::applicationLoop, and __ViperApplication_t::status.
Referenced by ViperApplicationStart().
__ViperEmptyLoopNoCall()
static void __ViperEmptyLoopNoCall (ViperApplication_t * app) [static]
These function is internal helper functions.
Definition at line 11 of file application.c.
Referenced by ViperApplicationCreate().
__ViperRenderLoopNoCall()
static void __ViperRenderLoopNoCall (ViperApplication_t * app) [static]
Definition at line 14 of file application.c.
References ViperGLFWwindow_t::data, __ViperApplication_t::opengl, __ViperApplication_t::status, VIPER_APPLICATION_STATUS_EXIT, and ViperOpenGL_t::window.
Referenced by ViperApplicationCreate().
ViperApplicationCreate()
int ViperApplicationCreate (ViperApplication_t * app, const ViperApplicationCreateInfo_t * info)
This function can either be called directly or using the create function, it will initiliaze the struct using the data provided in the ApplicationCreateInfo_t.
Parameters
info->name :: is the application name that will be used for the application\ and for the window if graphics are used.
Definition at line 51 of file application.c.
References __ViperEmptyLoopNoCall(), __ViperRenderLoop, __ViperRenderLoopNoCall(), __ViperApplication_t::applicationLoop, ViperApplicationCreateInfo_t::applicationLoop, ViperApplicationCreateInfo_t::flags, __ViperApplication_t::name, ViperApplicationCreateInfo_t::name, __ViperApplication_t::opengl, __ViperApplication_t::status, __ViperApplication_t::sType, VIPER_APPLICATION_FLAG_GRAPHICS_OPENGL, VIPER_APPLICATION_FLAG_GRAPHICS_VULKAN, VIPER_APPLICATION_STATUS_RUNNING, VIPER_STRUCTURE_TYPE_APPLICATION, ViperLogDebug, ViperLogError, ViperOpenGLInit(), ViperRenderLoopOpenGL(), ViperStringCreate(), ViperVulkanInit(), and __ViperApplication_t::vulkan.
Referenced by ViperCreate().
ViperApplicationStart()
void ViperApplicationStart (ViperApplication_t * app)
Definition at line 92 of file application.c.
References __ViperApplicationLoop().
Variable Documentation
__ViperRenderLoop
void(* __ViperRenderLoop) (ViperApplication_t *app) (ViperApplication_t * app) = &__ViperEmptyLoopNoCall [static]
This is local global varible to allows the user to switch between multiple rendering methods.
Parameters
app :: is the Application_t struct for the program.
default the __EmptyLoopNoCall function is used as a placeholder.
Definition at line 29 of file application.c.
Referenced by __ViperApplicationLoop(), and ViperApplicationCreate().