include/viper/application/application.h File Reference
#include <viper/types.h>
Functions
int ViperApplicationCreate (ViperApplication_t *app, const ViperApplicationCreateInfo_t *info)
This function can either be called directly or using the create function, it will initiliaze the struct using the data provided in the ApplicationCreateInfo_t.
void ViperApplicationStart (ViperApplication_t *app)
Function Documentation
ViperApplicationCreate()
int ViperApplicationCreate (ViperApplication_t * app, const ViperApplicationCreateInfo_t * info) [extern]
This function can either be called directly or using the create function, it will initiliaze the struct using the data provided in the ApplicationCreateInfo_t.
Parameters
info->name :: is the application name that will be used for the application\ and for the window if graphics are used.
Definition at line 51 of file application.c.
References __ViperEmptyLoopNoCall(), __ViperRenderLoop, __ViperRenderLoopNoCall(), __ViperApplication_t::applicationLoop, ViperApplicationCreateInfo_t::applicationLoop, ViperApplicationCreateInfo_t::flags, __ViperApplication_t::name, ViperApplicationCreateInfo_t::name, __ViperApplication_t::opengl, __ViperApplication_t::status, __ViperApplication_t::sType, VIPER_APPLICATION_FLAG_GRAPHICS_OPENGL, VIPER_APPLICATION_FLAG_GRAPHICS_VULKAN, VIPER_APPLICATION_STATUS_RUNNING, VIPER_STRUCTURE_TYPE_APPLICATION, ViperLogDebug, ViperLogError, ViperOpenGLInit(), ViperRenderLoopOpenGL(), ViperStringCreate(), ViperVulkanInit(), and __ViperApplication_t::vulkan.
Referenced by ViperCreate().
ViperApplicationStart()
void ViperApplicationStart (ViperApplication_t * app) [extern]
Definition at line 92 of file application.c.
References __ViperApplicationLoop().