source/memory/create.c File Reference
#include "viper/memory/utils.h"
#include "viper/types.h"
#include "viper/types/str.h"
#include <viper/memory/create.h>
#include <viper/utils/stringer.h>
#include <viper/application/application.h>
Functions
void * ViperCreate (int64_t type, void *ptr,...)
void * ViperDelete (void *ptr)
Function Documentation
ViperCreate()
void * ViperCreate (int64_t type, void * ptr, ...)
Definition at line 8 of file create.c.
References ViperGenericStruct_t::sType, VIPER_STRUCTURE_TYPE_APPLICATION, VIPER_STRUCTURE_TYPE_STRING, VIPER_STRUCTURE_TYPE_UNKOWN, ViperApplicationCreate(), ViperGetStructureSize(), and ViperStringCreate().
ViperDelete()
void * ViperDelete (void * ptr)
Definition at line 39 of file create.c.
References ViperGenericStruct_t::sType, VIPER_STRUCTURE_TYPE_STRING, and ViperStringDelete().