source/io/file.c File Reference
#include "viper/types/memory.h"
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <viper/io/file.h>
#include <viper/debug/logger.h>
Functions
ViperFile_t * ViperLoadFile (const char *file)
ViperFile_t * ViperUnloadFile (ViperFile_t *file)
int8_t ViperBufferFlushToFile (const char *fileName, ViperBuffer_t *buffer)
Function Documentation
ViperBufferFlushToFile()
int8_t ViperBufferFlushToFile (const char * fileName, ViperBuffer_t * buffer)
Definition at line 63 of file file.c.
References ViperBuffer_t::bytes, ViperBuffer_t::str, and ViperLogError.
ViperLoadFile()
ViperFile_t * ViperLoadFile (const char * file)
Definition at line 13 of file file.c.
References ViperFile_t::buffer, ViperBuffer_t::bytes, ViperBuffer_t::data, ViperLogEmergancy, and ViperLogError.
Referenced by ViperCreateShaderOpenGL(), and ViperImageLoad().
ViperUnloadFile()
ViperFile_t * ViperUnloadFile (ViperFile_t * file)
Definition at line 50 of file file.c.
References ViperFile_t::buffer, ViperBuffer_t::bytes, ViperBuffer_t::ptr, and ViperLogCritical.
Referenced by ViperCreateShaderOpenGL(), and ViperImageLoad().