source/io/images.c File Reference
#include "viper/types/images.h"
#include "viper/io/file.h"
#include "viper/types/file.h"
#include <viper/debug/logger.h>
#include <viper/io/images.h>
#include <stdio.h>
#include <string.h>
Functions
int64_t ViperImageFindType (uint8_t *h)
This function takes a image files and try to find the type that the iamge is encoded in.
ViperImage_t * ViperImageLoad (const char *path)
Variables
static const uint8_t __jpg [] = { 0xFF, 0xD8, 0xFF }
static const uint8_t __png [] = { 137, 80, 78, 71, 13, 10, 26, 10 }
static const uint8_t __ppm [] = { 0x50, 0x36 }
Function Documentation
ViperImageFindType()
int64_t ViperImageFindType (uint8_t * h)
This function takes a image files and try to find the type that the iamge is encoded in.
Parameters
h :: the magic/header bytes.
Returns
Returns the image type.
Note
this function have no length restriction so ensure that \ the file is at least longer then the JPG magic bytes.
Definition at line 24 of file images.c.
References __jpg, __png, __ppm, VIPER_IMAGE_JPG_HEADER, VIPER_IMAGE_NULLPTR_HEADER, VIPER_IMAGE_PNG_HEADER, VIPER_IMAGE_PPM_HEADER, and VIPER_IMAGE_UNKOWN_HEADER.
Referenced by ViperImageLoad().
ViperImageLoad()
ViperImage_t * ViperImageLoad (const char * path)
Definition at line 54 of file images.c.
References ViperFile_t::buffer, ViperBuffer_t::ptr, VIPER_IMAGE_JPG_HEADER, VIPER_IMAGE_PNG_HEADER, VIPER_IMAGE_PPM_HEADER, ViperImageFindType(), ViperLoadFile(), ViperLogDebug, ViperLogEmergancy, ViperLogError, ViperLogWarning, and ViperUnloadFile().
Variable Documentation
__jpg
const uint8_t __jpg[] = { 0xFF, 0xD8, 0xFF } [static]
Definition at line 9 of file images.c.
Referenced by ViperImageFindType().
__png
const uint8_t __png[] = { 137, 80, 78, 71, 13, 10, 26, 10 } [static]
Definition at line 10 of file images.c.
Referenced by ViperImageFindType().
__ppm
const uint8_t __ppm[] = { 0x50, 0x36 } [static]
Definition at line 11 of file images.c.
Referenced by ViperImageFindType().