source/vulkan/instance.c File Reference
#include "viper/threading/master.h"
#include <viper/debug/logger.h>
#include <viper/vulkan/instance.h>
Functions
char ** ViperVulkanGetExtensions (uint32_t *count, const char **extensions)
count is used both for input and the resulting size of the new list
int ViperVulkanInstanceCreate (ViperApplication_t *app, ViperVulkan_t *vk)
This function will create a VkInstance using the Vulkan_t->instance varible, allowing for smoth start of the application.
Variables
static const char * _VIPER_ENGINE_NAME = "viper"
Hardcoding the name of the engine no reason to make it dymanic.
static const char * _VIPER_INSTANCE_EXTENSIONS []
Additional dependencies for the instance.
Function Documentation
ViperVulkanGetExtensions()
char ** ViperVulkanGetExtensions (uint32_t * count, const char ** extensions)
count is used both for input and the resulting size of the new list
Parameters
count :: Is used first to tell the function how many extensions \ are provided and then as the return of how many extensions are returned.
extensions :: Is the list of the extensions that will be copied.
Returns
This function will return the extensions in a new list, this \ list needs to be freed by the developer.
Definition at line 27 of file instance.c.
References ViperLogDebug.
Referenced by ViperVulkanInstanceCreate().
ViperVulkanInstanceCreate()
int ViperVulkanInstanceCreate (ViperApplication_t * app, ViperVulkan_t * vk)
This function will create a VkInstance using the Vulkan_t->instance varible, allowing for smoth start of the application.
If Application_t->name is set this will be used for the application name, as for the engine name its hard coded to Viper.
Parameters
app :: Is the main Application_t struct.
vk :: Is the Vulkan_t struct that contains all the vulkan spesfic data.
Definition at line 66 of file instance.c.
References _VIPER_INSTANCE_EXTENSIONS, ViperString_t::data, ViperVkInstance_t::data, ViperVulkan_t::instance, __ViperApplication_t::name, ViperLogDebug, ViperLogError, ViperUnsafeStructAccess, ViperUnsafeStructRelease, and ViperVulkanGetExtensions().
Referenced by ViperVulkanInit().
Variable Documentation
_VIPER_ENGINE_NAME
const char* _VIPER_ENGINE_NAME = "viper" [static]
Hardcoding the name of the engine no reason to make it dymanic.
Definition at line 9 of file instance.c.
_VIPER_INSTANCE_EXTENSIONS
const char* _VIPER_INSTANCE_EXTENSIONS[] [static]
Initial value:
= {
}
Additional dependencies for the instance.
Definition at line 14 of file instance.c.
Referenced by ViperVulkanInstanceCreate().