include/viper/utils/integer.h File Reference
#include <viper/types.h>
Functions
int64_t ViperIntegerStringLength (int64_t value, int32_t base)
A simple function for getting the length of a integer in string format.
int64_t ViperItoa (int64_t value, char *buffer, int64_t length, int32_t base)
The non standard itoa function is very useful but to be more cross platform for no extra cost this is a simple implementation, it use the _numberTable to find the correct charter.
int64_t ViperAtoi (const char *buffer)
Function Documentation
ViperAtoi()
int64_t ViperAtoi (const char * buffer) [extern]
Definition at line 83 of file integer.c.
References ViperFindNonNumeric().
Referenced by ExecuteItoaAtoiTest(), and ViperImageDecodePPM6().
ViperIntegerStringLength()
int64_t ViperIntegerStringLength (int64_t value, int32_t base) [extern], [inline]
A simple function for getting the length of a integer in string format.
Parameters
value :: The integer value to messure.
base :: The base of the return value.
Definition at line 23 of file integer.c.
References ViperLog().
Referenced by ViperImageDecodePPM6(), ViperImageEncodePPM6(), and ViperItoa().
ViperItoa()
int64_t ViperItoa (int64_t value, char * buffer, int64_t length, int32_t base) [extern]
The non standard itoa function is very useful but to be more cross platform for no extra cost this is a simple implementation, it use the _numberTable to find the correct charter.
Parameters
value :: is the value to be converted into a string
buffer :: is the buffer that will be used for the output
length :: is the length of the buffer
base :: is the base that the value will be returned in 2, 4, 8, 10 and so on.
Returns
Is the length of the new string in int64_t format \ and will return -1 if the function is had an error
Definition at line 40 of file integer.c.
References _viperNumberTable, ViperIntegerStringLength(), and ViperLogError.
Referenced by __ViperPercentage(), ExecuteItoaAtoiTest(), ExecuteItoaCompersionTest(), ExecuteItoaCrashTest(), and ViperImageEncodePPM6().