include/viper/io/images.h File Reference
#include <viper/types/images.h>
Functions
ViperImage_t * ViperImageLoad (const char *path)
Function Documentation
ViperImageLoad()
ViperImage_t * ViperImageLoad (const char * path) [extern]
Definition at line 54 of file images.c.
References ViperFile_t::buffer, ViperBuffer_t::ptr, VIPER_IMAGE_JPG_HEADER, VIPER_IMAGE_PNG_HEADER, VIPER_IMAGE_PPM_HEADER, ViperImageFindType(), ViperLoadFile(), ViperLogDebug, ViperLogEmergancy, ViperLogError, ViperLogWarning, and ViperUnloadFile().