source/algorithms/linked_list.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <viper/types.h>
#include <viper/types/linked_list.h>
#include <viper/algorithms/linked_list.h>
#include <viper/types/structs.h>
#include <viper/types/varibles.h>
#include <viper/debug/logger.h>
Macros
#define CASE_VARIBLE_ADD(STRUCTURE_TYPE, LIST, NODES, TYPE, VAR_TYPE, COUNT, VA, GOTO)
#define CASE_STRUCTURE_ADD(STRUCTURE_TYPE, LIST, NODES, TYPE, COUNT, VA, GOTO)
Functions
int __ViperLinkedListAddItemVA (ViperLinkedList_t *list, int64_t count, va_list args)
This function will add items to a existing LinkedList_t object, the objects or variables needs to match the stored items.
ViperLinkedList_t ViperLinkedListInit (ViperLinkedList_t *list, int64_t type, int64_t count,...)
This function will set the structures memory to zero and the sType to the type tat is passed in, after this is done object will be added to the list itself.
int __ViperLinkedListAddItem (ViperLinkedList_t *list, int64_t count,...)
Wrapper function for __LinkedListAddItemVA.
int LinkedListDeleteItem (ViperLinkedList_t *list, uint64_t index)
int LinkedListInsertItem (ViperLinkedList_t *list, uint64_t index,...)
void * __LinkedListGetItem (ViperLinkedList_t *list, uint64_t index)
This function is the underlaying function for retriving items in a linked list.
ViperLinkedList_t * LinkedListClear (ViperLinkedList_t *list)
ViperLinkedList_t * LinkedListDelete (ViperLinkedList_t *list)
void * LinkedListToArray (ViperLinkedList_t *list)
Macro Definition Documentation
CASE_STRUCTURE_ADD
#define CASE_STRUCTURE_ADD(STRUCTURE_TYPE, LIST, NODES, TYPE, COUNT, VA, GOTO)
Value:
        case STRUCTURE_TYPE: {\
        for (int64_t i = 0; i < COUNT; i++) { \
            TYPE* ptr = va_arg(VA, TYPE*); \
            NODES[i].data = malloc(sizeof(TYPE)); \
            memcpy(NODES[i].data, ptr, sizeof(TYPE)); \
            \
            if (NULL != list->head && NULL != list->tail) { \
                LIST->tail->pNext = &NODES[i]; \
            } else { \
                ViperLogDebug("Creating new list %s", #TYPE); \
            } \
            NODES[i].pPrivous = LIST->tail; \
            LIST->tail = &NODES[i]; \
        } \
    } break
Definition at line 34 of file linked_list.c.
CASE_VARIBLE_ADD
#define CASE_VARIBLE_ADD(STRUCTURE_TYPE, LIST, NODES, TYPE, VAR_TYPE, COUNT, VA, GOTO)
Value:
        case STRUCTURE_TYPE: {\
        TYPE* data = (TYPE*)calloc(count, sizeof(TYPE)); \
        \
        if (NULL == data) { \
            ViperLogError("Failed to alloacte memory for #TYPE"); \
            goto GOTO; \
        } \
        \
        for (int64_t i = 0; i < COUNT; i++) { \
            data->sType = STRUCTURE_TYPE; \
            data->value = va_arg(VA, VAR_TYPE); \
            \
            NODES[i].data = data; \
            \
            if (NULL != list->head && NULL != list->tail) { \
                LIST->tail->pNext = &NODES[i]; \
            } else { \
                ViperLogDebug("Creating new list %s", #TYPE); \
            } \
            NODES[i].pPrivous = LIST->tail; \
            LIST->tail = &NODES[i]; \
        } \
    } break
Definition at line 10 of file linked_list.c.
Function Documentation
__LinkedListGetItem()
void * __LinkedListGetItem (ViperLinkedList_t * list, uint64_t index)
This function is the underlaying function for retriving items in a linked list.
Parameters
list :: The list object.
index :: The index where the obejct is stored.
Definition at line 154 of file linked_list.c.
References __LinkedListNode_t::data, ViperLinkedList_t::head, __LinkedListNode_t::pNext, and ViperLogDebug.
__ViperLinkedListAddItem()
int __ViperLinkedListAddItem (ViperLinkedList_t * list, int64_t count, ...)
Wrapper function for __LinkedListAddItemVA.
Parameters
list :: the list that will have the items added.
count :: the count of the new items that will be added.
Definition at line 128 of file linked_list.c.
References __ViperLinkedListAddItemVA().
__ViperLinkedListAddItemVA()
int __ViperLinkedListAddItemVA (ViperLinkedList_t * list, int64_t count, va_list args)
This function will add items to a existing LinkedList_t object, the objects or variables needs to match the stored items.
Parameters
list :: the list that will have the items added.
count :: the count of the new items that will be added.
args :: the va_list with the itmes stored in it.
Definition at line 58 of file linked_list.c.
References CASE_STRUCTURE_ADD, CASE_VARIBLE_ADD, ViperLinkedList_t::head, __LinkedListNode_t::pNext, __LinkedListNode_t::pPrivous, ViperLinkedList_t::sType, ViperLinkedList_t::tail, VIPER_STRUCTURE_TYPE_APPLICATION, VIPER_STRUCTURE_TYPE_VULKAN, VIPER_VARIABLE_TYPE_FLOAT, VIPER_VARIABLE_TYPE_INT, ViperLogDebug, and ViperLogError.
Referenced by __ViperLinkedListAddItem(), and ViperLinkedListInit().
LinkedListClear()
ViperLinkedList_t * LinkedListClear (ViperLinkedList_t * list)
Definition at line 167 of file linked_list.c.
LinkedListDelete()
ViperLinkedList_t * LinkedListDelete (ViperLinkedList_t * list)
Definition at line 171 of file linked_list.c.
LinkedListDeleteItem()
int LinkedListDeleteItem (ViperLinkedList_t * list, uint64_t index)
Definition at line 139 of file linked_list.c.
LinkedListInsertItem()
int LinkedListInsertItem (ViperLinkedList_t * list, uint64_t index, ...)
Definition at line 143 of file linked_list.c.
LinkedListToArray()
void * LinkedListToArray (ViperLinkedList_t * list)
Definition at line 175 of file linked_list.c.
ViperLinkedListInit()
ViperLinkedList_t ViperLinkedListInit (ViperLinkedList_t * list, int64_t type, int64_t count, ...)
This function will set the structures memory to zero and the sType to the type tat is passed in, after this is done object will be added to the list itself.
Note
This function will conver basic type like int into Int_t, \ so when using this function keep this in mind.
Parameters
list :: is the object that will be used to store information.
type :: is the type that will be use STRUCTURE_TYPE_XXX or VARBIALE_TYPE_XXX
count :: is the number passed in to the function.
... :: is the actual values.
Returns
This function will return a copy of the LinkedList_t.
Definition at line 108 of file linked_list.c.
References __ViperLinkedListAddItemVA(), and ViperLinkedList_t::sType.