source/debug/logger.c File Reference
#include <viper/debug/logger.h>
#include <viper/io/printer.h>
#include <stdarg.h>
Functions
void __ViperLogger (ViperLogInfo_t info, const char *restrict format,...)
Variables
static int64_t __logLevelMax = VIPER_LOG_LEVEL_EMERGANCY
static int64_t __logLevelMin = VIPER_LOG_LEVEL_DEBUG
Function Documentation
__ViperLogger()
void __ViperLogger (ViperLogInfo_t info, const char *restrict format, ...)
Definition at line 8 of file logger.c.
References __logLevelMax, __logLevelMin, ViperBuffer_t::bytes, ViperLogInfo_t::logLevel, ViperBuffer_t::ptr, ViperBuffer_t::str, VIPER_LOG_LEVEL_ALERT, VIPER_LOG_LEVEL_CRITICAL, VIPER_LOG_LEVEL_DEBUG, VIPER_LOG_LEVEL_EMERGANCY, VIPER_LOG_LEVEL_ERROR, VIPER_LOG_LEVEL_INFO, VIPER_LOG_LEVEL_NOTICE, VIPER_LOG_LEVEL_WARNING, VIPER_PRINT_STDERR, ViperPrintFlush(), ViperPrintNSBUF(), and ViperPrintNSBUFVA().
Variable Documentation
__logLevelMax
int64_t __logLevelMax = VIPER_LOG_LEVEL_EMERGANCY [static]
Definition at line 5 of file logger.c.
Referenced by __ViperLogger().
__logLevelMin
int64_t __logLevelMin = VIPER_LOG_LEVEL_DEBUG [static]
Definition at line 6 of file logger.c.
Referenced by __ViperLogger().