include/viper/images/ppm.h File Reference
#include <stdint.h>
#include <viper/types/memory.h>
#include <viper/types/images.h>
Functions
int8_t ViperImageDecodePPM6 (ViperImage_t *image, ViperBuffer_t const *data)
This function takes a valid P6 ppm raw file and returns it as a ViperImage_t, the function calling this function must check that the image has a valid P6 magic header.
ViperBuffer_t * ViperImageEncodePPM6 (ViperImage_t const *image)
Function Documentation
ViperImageDecodePPM6()
int8_t ViperImageDecodePPM6 (ViperImage_t * image, ViperBuffer_t const * data) [extern]
This function takes a valid P6 ppm raw file and returns it as a ViperImage_t, the function calling this function must check that the image has a valid P6 magic header.
Parameters
image :: Is the output varible.
data :: Is the raw data for the image.
Returns
0 is success and -1 is faliure.
Definition at line 20 of file ppm.c.
References ViperImage_t::buffer, ViperBuffer_t::bytes, ViperBuffer_t::ptr, ViperImage_t::resultion, ViperBuffer_t::str, VIPER_INT_MAX_U16, VIPER_INT_MAX_U32, VIPER_INT_MAX_U64, VIPER_INT_MAX_U8, ViperAtoi(), ViperFindNextChar(), ViperIntegerStringLength(), ViperSkipLine(), ViperVectorInt2_t::x, and ViperVectorInt2_t::y.
ViperImageEncodePPM6()
ViperBuffer_t * ViperImageEncodePPM6 (ViperImage_t const * image) [extern]
Definition at line 95 of file ppm.c.
References ViperImage_t::buffer, ViperBuffer_t::bytes, ViperBuffer_t::ptr, ViperImage_t::resultion, ViperBuffer_t::str, ViperIntegerStringLength(), ViperItoa(), ViperVectorInt2_t::x, and ViperVectorInt2_t::y.