source/printer.c File Reference
#include <unistd.h>
#include <vulkan/vulkan.h>
#include <viper/printer.h>
#include <viper/types.h>
#include <viper/utils.h>
#include <stdio.h>
#include <vulkan/vulkan_core.h>
Data Structures
struct PrintData_t
This struct is a internal data type to help with passing along crusial data to the next function.
Functions
static int64_t __FlushBuffer (PrintData_t *data)
This function will check if the buffer exceeds the max buffer value, if so then the buffer will be flushed and the bufferUsed varible will be reset.
static int64_t __GetErrorNumber (PrintData_t *data, va_list va)
This function is used to convert errno number into something a bit more readable and adding it to the log print buffer.
static int64_t __CopyString (PrintData_t *data, va_list va)
This function will extract the va_list string and addit to the buffer so it will be printed.
static int64_t __VulkanResultToString (PrintData_t *data, va_list va)
static int64_t __Dollar (PrintData_t *data, va_list va)
Instead of wasting time on parsing in the _Percentage function these function will handle more complex parsing allowing for faster parsing over all.
static int64_t __Percentage (PrintData_t *data, va_list va)
This function is the faster alternative to _Dollar allowing for less time spent on the printing parsing.
int64_t PrintFlush (int stream, Buffer_t *buffer, int64_t used)
This function is to flush the buffer for all the print function or if the above function does so.
int64_t PrintNSBUFVA (int stream, Buffer_t *buffer, int64_t used, const char *format, va_list va)
This function is the main print function all the other function and allows the most freedom when printing, but it also requires more setup over the smaller functions.
int64_t PrintNSBUF (int stream, Buffer_t *buffer, int64_t used, const char *format,...)
PrintNSBF or [ Print No-buffer Stream Used Format ] is a print function wrapping PrintNSBFVA allowing for simpler calls.
int64_t PrintNSBFVA (int stream, Buffer_t *buffer, const char *format, va_list va)
int64_t PrintNSBF (int stream, Buffer_t *buffer, const char *format,...)
int64_t PrintSBFVA (int stream, Buffer_t *buffer, const char *format, va_list va)
int64_t PrintSBF (int stream, Buffer_t *buffer, const char *format,...)
int64_t PrintSFVA (int stream, const char *format, va_list va)
int64_t PrintFVA (const char *format, va_list va)
int64_t PrintSF (int stream, const char *format,...)
int64_t PrintF (const char *format,...)
The functions mimics the printf function, but is thread safe and have more options or will have.
int64_t Print (const char *msg)
The simplest function for printting with no formatting.
Function Documentation
__CopyString()
static int64_t __CopyString (PrintData_t * data, va_list va) [static]
This function will extract the va_list string and addit to the buffer so it will be printed.
Definition at line 53 of file printer.c.
References __FlushBuffer(), PrintData_t::buffer, PrintData_t::bufferUsed, Buffer_t::bytes, and Buffer_t::str.
Referenced by __Dollar(), and __Percentage().
__Dollar()
static int64_t __Dollar (PrintData_t * data, va_list va) [inline], [static]
Instead of wasting time on parsing in the _Percentage function these function will handle more complex parsing allowing for faster parsing over all.
Definition at line 145 of file printer.c.
References __CopyString(), PrintData_t::buffer, PrintData_t::bufferUsed, PrintData_t::current, and Buffer_t::str.
Referenced by PrintNSBUFVA().
__FlushBuffer()
static int64_t __FlushBuffer (PrintData_t * data) [static]
This function will check if the buffer exceeds the max buffer value, if so then the buffer will be flushed and the bufferUsed varible will be reset.
Definition at line 27 of file printer.c.
References PrintData_t::buffer, PrintData_t::bufferUsed, Buffer_t::bytes, Buffer_t::ptr, and PrintData_t::stream.
Referenced by __CopyString().
__GetErrorNumber()
static int64_t __GetErrorNumber (PrintData_t * data, va_list va) [static]
This function is used to convert errno number into something a bit more readable and adding it to the log print buffer.
Definition at line 40 of file printer.c.
References PrintData_t::buffer, PrintData_t::bufferUsed, Buffer_t::bytes, and Buffer_t::str.
Referenced by __Percentage().
__Percentage()
static int64_t __Percentage (PrintData_t * data, va_list va) [inline], [static]
This function is the faster alternative to _Dollar allowing for less time spent on the printing parsing.
b is used for binary
d is used for double
f is used for floats
h is used for hexdecimal
i is used for int
n is used print errno
o is used for octets
s is used for c strings
S is used for String_t
t is used to print the current time with no argument
v is used for printing VkResult
Definition at line 174 of file printer.c.
References __CopyString(), __GetErrorNumber(), __VulkanResultToString(), PrintData_t::buffer, PrintData_t::bufferUsed, Buffer_t::bytes, PrintData_t::current, Itoa(), and Buffer_t::str.
Referenced by PrintNSBUFVA().
__VulkanResultToString()
static int64_t __VulkanResultToString (PrintData_t * data, va_list va) [static]
A very long switch with all the VkResult values
Definition at line 77 of file printer.c.
References PrintData_t::buffer, PrintData_t::bufferUsed, and Buffer_t::str.
Referenced by __Percentage().
Print()
int64_t Print (const char * msg)
The simplest function for printting with no formatting.
Parameters
msg :: the message.
Definition at line 373 of file printer.c.
References PrintF().
PrintF()
int64_t PrintF (const char * format, ...)
The functions mimics the printf function, but is thread safe and have more options or will have.
Parameters
msg :: The fomrated string for the input.
... :: Is va_arg list.
Definition at line 357 of file printer.c.
References PrintSFVA().
Referenced by Print().
PrintFlush()
int64_t PrintFlush (int stream, Buffer_t * buffer, int64_t used)
This function is to flush the buffer for all the print function or if the above function does so.
Parameters
stream :: The stream to output to like [ stdout, stderr or other stream ]
buffer :: Is the buffer that's used for storing the data.
used :: Allows the above function to set the buffer index
Definition at line 220 of file printer.c.
References Buffer_t::str.
Referenced by __Logger().
PrintFVA()
int64_t PrintFVA (const char * format, va_list va)
Definition at line 334 of file printer.c.
References PrintSFVA().
PrintNSBF()
int64_t PrintNSBF (int stream, Buffer_t * buffer, const char * format, ...)
Definition at line 299 of file printer.c.
References PrintNSBFVA().
PrintNSBFVA()
int64_t PrintNSBFVA (int stream, Buffer_t * buffer, const char * format, va_list va)
Definition at line 295 of file printer.c.
References PrintNSBUFVA().
Referenced by PrintNSBF(), and PrintSBFVA().
PrintNSBUF()
int64_t PrintNSBUF (int stream, Buffer_t * buffer, int64_t used, const char * format, ...)
PrintNSBF or [ Print No-buffer Stream Used Format ] is a print function wrapping PrintNSBFVA allowing for simpler calls.
Parameters
stream is the output stream like [ stdout or stderr ]
buffer is used to supply the buffer to the function
used is to tell the function if the buffer has a pre-existing used space
format is the input format of the va_list
... is the actual data described in the format string
Definition at line 286 of file printer.c.
References PrintNSBUFVA().
Referenced by __Logger().
PrintNSBUFVA()
int64_t PrintNSBUFVA (int stream, Buffer_t * buffer, int64_t used, const char * format, va_list va)
This function is the main print function all the other function and allows the most freedom when printing, but it also requires more setup over the smaller functions.
Parameters
stream :: The stream to output to like [ stdout, stderr or other stream ]
buffer :: Is the buffer that's used for storing the data.
used :: Allows the above function to set the buffer index
format :: The formatting string for the va_list.
va :: Is the va_list.
for loop
Definition at line 235 of file printer.c.
References __Dollar(), __Percentage(), PrintData_t::current, Buffer_t::str, and PrintData_t::stream.
Referenced by __Logger(), PrintNSBFVA(), and PrintNSBUF().
PrintSBF()
int64_t PrintSBF (int stream, Buffer_t * buffer, const char * format, ...)
Definition at line 314 of file printer.c.
References PrintSBFVA().
PrintSBFVA()
int64_t PrintSBFVA (int stream, Buffer_t * buffer, const char * format, va_list va)
Definition at line 308 of file printer.c.
References Buffer_t::bytes, PrintNSBFVA(), and Buffer_t::str.
Referenced by PrintSBF(), and PrintSFVA().
PrintSF()
int64_t PrintSF (int stream, const char * format, ...)
Definition at line 338 of file printer.c.
References PrintSFVA().
PrintSFVA()
int64_t PrintSFVA (int stream, const char * format, va_list va)
Definition at line 323 of file printer.c.
References Buffer_t::bytes, MEMORY_2KB, and PrintSBFVA().
Referenced by PrintF(), PrintFVA(), and PrintSF().