include/viper/io/printer.h File Reference
#include <stdlib.h>
#include <string.h>
#include <viper/types.h>
Macros
#define VIPER_PRINT_STDOUT 1
#define VIPER_PRINT_STDERR 2
Functions
int64_t ViperPrintFlush (int stream, ViperBuffer_t *buffer, int64_t used)
int64_t ViperPrintNSBUFVA (int stream, ViperBuffer_t *buffer, int64_t used, const char *format, va_list va)
int64_t ViperPrintNSBFVA (int stream, ViperBuffer_t *buffer, const char *format, va_list va)
int64_t ViperPrintSBFVA (int stream, ViperBuffer_t *buffer, const char *format, va_list va)
int64_t ViperPrintSFVA (int stream, const char *format, va_list va)
int64_t ViperPrintFVA (const char *format, va_list va)
int64_t ViperPrintNSBUF (int stream, ViperBuffer_t *buffer, int64_t used, const char *format,...)
int64_t ViperPrintNSBF (int stream, ViperBuffer_t *buffer, const char *format,...)
int64_t ViperPrintSF (int stream, const char *format,...)
int64_t ViperPrintF (const char *format,...)
int64_t ViperPrint (const char *msg)
The simplest function for printting with no formatting.
Macro Definition Documentation
VIPER_PRINT_STDERR
#define VIPER_PRINT_STDERR 2
Definition at line 10 of file printer.h.
VIPER_PRINT_STDOUT
#define VIPER_PRINT_STDOUT 1
Definition at line 9 of file printer.h.
Function Documentation
ViperPrint()
int64_t ViperPrint (const char * msg) [extern]
The simplest function for printting with no formatting.
Parameters
msg :: the message.
Definition at line 374 of file printer.c.
References ViperPrintF().
ViperPrintF()
int64_t ViperPrintF (const char * format, ...) [extern]
Referenced by ExecuteItoaAtoiTest(), ExecuteItoaCompersionTest(), ExecuteItoaCrashTest(), ExecuteLogTest(), and ViperDeflateDecompress().
ViperPrintFlush()
int64_t ViperPrintFlush (int stream, ViperBuffer_t * buffer, int64_t used) [extern]
Referenced by __ViperLogger().
ViperPrintFVA()
int64_t ViperPrintFVA (const char * format, va_list va) [extern]
ViperPrintNSBF()
int64_t ViperPrintNSBF (int stream, ViperBuffer_t * buffer, const char * format, ...) [extern]
Definition at line 301 of file printer.c.
References ViperPrintNSBFVA().
ViperPrintNSBFVA()
int64_t ViperPrintNSBFVA (int stream, ViperBuffer_t * buffer, const char * format, va_list va) [extern]
ViperPrintNSBUF()
int64_t ViperPrintNSBUF (int stream, ViperBuffer_t * buffer, int64_t used, const char * format, ...) [extern]
Referenced by __ViperLogger().
ViperPrintNSBUFVA()
int64_t ViperPrintNSBUFVA (int stream, ViperBuffer_t * buffer, int64_t used, const char * format, va_list va) [extern]
Referenced by __ViperLogger().
ViperPrintSBFVA()
int64_t ViperPrintSBFVA (int stream, ViperBuffer_t * buffer, const char * format, va_list va) [extern]
ViperPrintSF()
int64_t ViperPrintSF (int stream, const char * format, ...) [extern]
ViperPrintSFVA()
int64_t ViperPrintSFVA (int stream, const char * format, va_list va) [extern]