source/opengl/shader.c File Reference
#include "viper/memory/create.h"
#include <GL/glew.h>
#include <stdint.h>
#include <viper/types/file.h>
#include <viper/types/glsl.h>
#include <viper/types/opengl.h>
#include <viper/io/file.h>
#include <viper/debug/logger.h>
Functions
void ViperDeleteShadersOpenGL (int *compute, int *fragment, int *geometric, int *tesslation, int *vertex)
The ViperDeleteShadersOpenGL function is used for clearing out shader objects in OpenGL.
int8_t ViperCreateShaderOpenGL (int type, const char *path)
int8_t ViperLoadShadersOpenGL (ViperShaderOpenGL_t *shader, ViperShaderLocationsGLSL_t paths)
Function Documentation
ViperCreateShaderOpenGL()
int8_t ViperCreateShaderOpenGL (int type, const char * path)
Definition at line 58 of file shader.c.
References ViperFile_t::buffer, ViperBuffer_t::str, ViperLoadFile(), ViperLogDebug, ViperLogError, and ViperUnloadFile().
Referenced by ViperLoadShadersOpenGL().
ViperDeleteShadersOpenGL()
void ViperDeleteShadersOpenGL (int * compute, int * fragment, int * geometric, int * tesslation, int * vertex)
The ViperDeleteShadersOpenGL function is used for clearing out shader objects in OpenGL.
Parameters
compute Pointer to the compute shader ID.
fragment Pointer to the fragment shader ID.
geometric Pointer to the geometric shader ID.
tessellation Pointer to the tessellation shader ID.
vertex Pointer to the vertex shader ID.
Definition at line 21 of file shader.c.
Referenced by ViperLoadShadersOpenGL().
ViperLoadShadersOpenGL()
int8_t ViperLoadShadersOpenGL (ViperShaderOpenGL_t * shader, ViperShaderLocationsGLSL_t paths)
Definition at line 93 of file shader.c.
References ViperShaderLocationsGLSL_t::compute, ViperShaderLocationsGLSL_t::fragment, ViperShaderLocationsGLSL_t::geometric, ViperShaderOpenGL_t::program, ViperShaderLocationsGLSL_t::vertex, ViperCreateShaderOpenGL(), ViperDeleteShadersOpenGL(), ViperLogDebug, ViperLogError, and ViperLogWarning.