source/debug/signal_handler.c File Reference
#include <execinfo.h>
#include <bits/types/siginfo_t.h>
#include <signal.h>
#include <unistd.h>
#include <viper/debug/signal_handler.h>
#include <viper/debug/logger.h>
Functions
static void __ViperSingalHandlerSEGSEGV ()
static void __ViperSingalHandler (int sig)
void ViperInitSignalHandler ()
Function Documentation
__ViperSingalHandler()
static void __ViperSingalHandler (int sig) [static]
Definition at line 19 of file signal_handler.c.
References __ViperSingalHandlerSEGSEGV().
Referenced by ViperInitSignalHandler().
__ViperSingalHandlerSEGSEGV()
static void __ViperSingalHandlerSEGSEGV () [inline], [static]
Definition at line 9 of file signal_handler.c.
References ViperLogEmergancy.
Referenced by __ViperSingalHandler().
ViperInitSignalHandler()
void ViperInitSignalHandler ()
Definition at line 30 of file signal_handler.c.
References __ViperSingalHandler().
Referenced by __ViperInternalSignalHandler().