source_test.c File Reference
#include "viper/io/parser.h"
#include "viper/debug/logger.h"
#include "viper/debug/signal_handler.h"
#include "viper/images/ppm.h"
#include "viper/io/images.h"
#include "viper/types/file.h"
#include "viper/types/images.h"
#include "viper/types/memory.h"
#include "viper/types/structs.h"
#include <viper/types.h>
#include <viper.h>
#include <viper/memory/create.h>
#include <viper/algorithms/linked_list.h>
#include <viper/memory/search.h>
#include <viper/io/file.h>
#include <viper/macros/utils.h>
#include <unistd.h>
#include <viper/debug/exceptions.h>
Macros
#define VIPER_USE_LIBRARY_MAIN
#define _POSIX_SOURCE
Functions
void Dryrun (ViperConfig_t *config, void *customData)
A example function of how to used the command line parser, using ViperAddParserOption will add this function to a list and then execute when stup is done.
void RenderLoop (ViperApplication_t *app)
This is a example of the Rendering Loop Function, it is used so that the sub-project can render objects without any complicated setup.
int64_t ViperSetup (ViperApplicationCreateInfo_t *info)
This function is provided so that the developer can supply there own data before the actual application starts.
int64_t ViperMain (ViperApplication_t *app)
The library main function this is only included if the VIPER_USE_LIBRARY_MAIN is defined.
Macro Definition Documentation
_POSIX_SOURCE
#define _POSIX_SOURCE
Definition at line 3 of file source_test.c.
VIPER_USE_LIBRARY_MAIN
#define VIPER_USE_LIBRARY_MAIN
Definition at line 2 of file source_test.c.
Function Documentation
Dryrun()
void Dryrun (ViperConfig_t * config, void * customData)
A example function of how to used the command line parser, using ViperAddParserOption will add this function to a list and then execute when stup is done.
Parameters
config ::
customData :: This is what ever the developer supplied \ int the ViperAddParserOption functon, its recommended to use \ sType to identify the structure type.
Definition at line 37 of file source_test.c.
References ViperLogDebug.
Referenced by ViperSetup().
RenderLoop()
void RenderLoop (ViperApplication_t * app)
This is a example of the Rendering Loop Function, it is used so that the sub-project can render objects without any complicated setup.
Parameters
app :: Is the supplied app struct with \ application inforamtion.
Definition at line 49 of file source_test.c.
Referenced by ViperSetup().
ViperMain()
int64_t ViperMain (ViperApplication_t * app)
The library main function this is only included if the VIPER_USE_LIBRARY_MAIN is defined.
Parameters
app :: is the application struct \ everthing in the application uses this struct.
Definition at line 83 of file source_test.c.
References ViperLogDebug.
ViperSetup()
int64_t ViperSetup (ViperApplicationCreateInfo_t * info)
This function is provided so that the developer can supply there own data before the actual application starts.
Parameters
info :: the configuration data.
Definition at line 69 of file source_test.c.
References ViperApplicationCreateInfo_t::applicationLoop, Dryrun(), RenderLoop(), and ViperAddParserOption().