tests/source.c File Reference
#include <stdio.h>
#include <viper.h>
#include <viper/types/tests.h>
#include "io/printer.c"
#include "utils/integer.c"
#include "math/log.c"
Functions
int Main (int arc, char *const *arv)
Function Documentation
Main()
int Main (int arc, char *const * arv)
Definition at line 12 of file source.c.
References ExecuteItoaTest(), ExecuteLogTests(), ExecutePrintTest(), ViperTestInfo_t::testFailed, and ViperTestInfo_t::testTotal.