source/io/printer.c File Reference
#include "viper/types/memory.h"
#include <unistd.h>
#include <vulkan/vulkan.h>
#include <viper/io/printer.h>
#include <viper/types.h>
#include <viper/utils/integer.h>
#include <stdio.h>
#include <vulkan/vulkan_core.h>
Data Structures
struct ViperPrintData_t
This struct is a internal data type to help with passing along crusial data to the next function.
Functions
static int64_t __ViperFlushBuffer (ViperPrintData_t *restrict data)
This function will check if the buffer exceeds the max buffer value, if so then the buffer will be flushed and the bufferUsed varible will be reset.
static int64_t __ViperGetErrorNumber (ViperPrintData_t *restrict data, va_list va)
This function is used to convert errno number into something a bit more readable and adding it to the log print buffer.
static int64_t __ViperCopyString (ViperPrintData_t *restrict data, va_list va)
This function will extract the va_list string and addit to the buffer so it will be printed.
static int64_t __ViperVulkanResultToString (ViperPrintData_t *restrict data, va_list va)
static int64_t __ViperDollar (ViperPrintData_t *restrict data, va_list va)
Instead of wasting time on parsing in the _Percentage function these function will handle more complex parsing allowing for faster parsing over all.
static int64_t __ViperPercentage (ViperPrintData_t *restrict data, va_list va)
This function is the faster alternative to _Dollar allowing for less time spent on the printing parsing.
int64_t ViperPrintFlush (int stream, ViperBuffer_t *restrict buffer, int64_t used)
This function is to flush the buffer for all the print function or if the above function does so.
int64_t ViperPrintNSBUFVA (int stream, ViperBuffer_t *restrict buffer, int64_t used, const char *restrict format, va_list va)
This function is the main print function all the other function and allows the most freedom when printing, but it also requires more setup over the smaller functions.
int64_t ViperPrintNSBUF (int stream, ViperBuffer_t *restrict buffer, int64_t used, const char *restrict format,...)
PrintNSBF or [ Print No-buffer Stream Used Format ] is a print function wrapping PrintNSBFVA allowing for simpler calls.
int64_t ViperPrintNSBFVA (int stream, ViperBuffer_t *restrict buffer, const char *restrict format, va_list va)
int64_t ViperPrintNSBF (int stream, ViperBuffer_t *buffer, const char *format,...)
int64_t ViperPrintSBFVA (int stream, ViperBuffer_t *restrict buffer, const char *restrict format, va_list va)
int64_t ViperPrintSBF (int stream, ViperBuffer_t *restrict buffer, const char *restrict format,...)
int64_t ViperPrintSFVA (int stream, const char *restrict format, va_list va)
int64_t ViperPrintFVA (const char *restrict format, va_list va)
int64_t ViperPrintSF (int stream, const char *restrict format,...)
int64_t ViperPrintF (const char *restrict format,...)
The functions mimics the printf function, but is thread safe and have more options or will have.
int64_t ViperPrint (const char *msg)
The simplest function for printting with no formatting.
Function Documentation
__ViperCopyString()
static int64_t __ViperCopyString (ViperPrintData_t *restrict data, va_list va) [inline], [static]
This function will extract the va_list string and addit to the buffer so it will be printed.
Definition at line 54 of file printer.c.
References __ViperFlushBuffer().
Referenced by __ViperDollar(), and __ViperPercentage().
__ViperDollar()
static int64_t __ViperDollar (ViperPrintData_t *restrict data, va_list va) [inline], [static]
Instead of wasting time on parsing in the _Percentage function these function will handle more complex parsing allowing for faster parsing over all.
Definition at line 146 of file printer.c.
References __ViperCopyString().
Referenced by ViperPrintNSBUFVA().
__ViperFlushBuffer()
static int64_t __ViperFlushBuffer (ViperPrintData_t *restrict data) [static]
This function will check if the buffer exceeds the max buffer value, if so then the buffer will be flushed and the bufferUsed varible will be reset.
Definition at line 28 of file printer.c.
References ViperPrintData_t::buffer, and ViperBuffer_t::bytes.
Referenced by __ViperCopyString().
__ViperGetErrorNumber()
static int64_t __ViperGetErrorNumber (ViperPrintData_t *restrict data, va_list va) [static]
This function is used to convert errno number into something a bit more readable and adding it to the log print buffer.
Definition at line 41 of file printer.c.
Referenced by __ViperPercentage().
__ViperPercentage()
static int64_t __ViperPercentage (ViperPrintData_t *restrict data, va_list va) [inline], [static]
This function is the faster alternative to _Dollar allowing for less time spent on the printing parsing.
b is used for binary
d is used for double
f is used for floats
h is used for hexdecimal
i is used for int
n is used print errno
o is used for octets
s is used for c strings
S is used for String_t
t is used to print the current time with no argument
v is used for printing VkResult
Definition at line 175 of file printer.c.
References __ViperCopyString(), __ViperGetErrorNumber(), __ViperVulkanResultToString(), and ViperItoa().
Referenced by ViperPrintNSBUFVA().
__ViperVulkanResultToString()
static int64_t __ViperVulkanResultToString (ViperPrintData_t *restrict data, va_list va) [static]
A very long switch with all the VkResult values
Definition at line 78 of file printer.c.
Referenced by __ViperPercentage().
ViperPrint()
int64_t ViperPrint (const char * msg)
The simplest function for printting with no formatting.
Parameters
msg :: the message.
Definition at line 374 of file printer.c.
References ViperPrintF().
ViperPrintF()
int64_t ViperPrintF (const char *restrict format, ...)
The functions mimics the printf function, but is thread safe and have more options or will have.
Parameters
msg :: The fomrated string for the input.
... :: Is va_arg list.
Definition at line 358 of file printer.c.
References ViperPrintSFVA().
Referenced by ExecutePrintTest(), and ViperPrint().
ViperPrintFlush()
int64_t ViperPrintFlush (int stream, ViperBuffer_t *restrict buffer, int64_t used)
This function is to flush the buffer for all the print function or if the above function does so.
Parameters
stream :: The stream to output to like [ stdout, stderr or other stream ]
buffer :: Is the buffer that's used for storing the data.
used :: Allows the above function to set the buffer index
Definition at line 222 of file printer.c.
ViperPrintFVA()
int64_t ViperPrintFVA (const char *restrict format, va_list va)
Definition at line 335 of file printer.c.
References ViperPrintSFVA().
ViperPrintNSBF()
int64_t ViperPrintNSBF (int stream, ViperBuffer_t * buffer, const char * format, ...)
Definition at line 301 of file printer.c.
References ViperPrintNSBFVA().
ViperPrintNSBFVA()
int64_t ViperPrintNSBFVA (int stream, ViperBuffer_t *restrict buffer, const char *restrict format, va_list va)
Definition at line 297 of file printer.c.
References ViperPrintNSBUFVA().
Referenced by ViperPrintNSBF(), and ViperPrintSBFVA().
ViperPrintNSBUF()
int64_t ViperPrintNSBUF (int stream, ViperBuffer_t *restrict buffer, int64_t used, const char *restrict format, ...)
PrintNSBF or [ Print No-buffer Stream Used Format ] is a print function wrapping PrintNSBFVA allowing for simpler calls.
Parameters
stream is the output stream like [ stdout or stderr ]
buffer is used to supply the buffer to the function
used is to tell the function if the buffer has a pre-existing used space
format is the input format of the va_list
... is the actual data described in the format string
Definition at line 288 of file printer.c.
References ViperPrintNSBUFVA().
ViperPrintNSBUFVA()
int64_t ViperPrintNSBUFVA (int stream, ViperBuffer_t *restrict buffer, int64_t used, const char *restrict format, va_list va)
This function is the main print function all the other function and allows the most freedom when printing, but it also requires more setup over the smaller functions.
Parameters
stream :: The stream to output to like [ stdout, stderr or other stream ]
buffer :: Is the buffer that's used for storing the data.
used :: Allows the above function to set the buffer index
format :: The formatting string for the va_list.
va :: Is the va_list.
for loop
Definition at line 237 of file printer.c.
References __ViperDollar(), __ViperPercentage(), ViperPrintData_t::current, and ViperPrintData_t::stream.
Referenced by ViperPrintNSBFVA(), and ViperPrintNSBUF().
ViperPrintSBF()
int64_t ViperPrintSBF (int stream, ViperBuffer_t *restrict buffer, const char *restrict format, ...)
Definition at line 316 of file printer.c.
References ViperPrintSBFVA().
ViperPrintSBFVA()
int64_t ViperPrintSBFVA (int stream, ViperBuffer_t *restrict buffer, const char *restrict format, va_list va)
Definition at line 310 of file printer.c.
References ViperPrintNSBFVA().
Referenced by ViperPrintSBF(), and ViperPrintSFVA().
ViperPrintSF()
int64_t ViperPrintSF (int stream, const char *restrict format, ...)
Definition at line 339 of file printer.c.
References ViperPrintSFVA().
ViperPrintSFVA()
int64_t ViperPrintSFVA (int stream, const char *restrict format, va_list va)
Definition at line 325 of file printer.c.
References ViperBuffer_t::bytes, MEMORY_256B, and ViperPrintSBFVA().
Referenced by ViperPrintF(), ViperPrintFVA(), and ViperPrintSF().