include/viper/utils/stringer.h File Reference
#include <viper/types.h>
#include <viper/debug/logger.h>
Functions
int64_t ViperStringCreate (ViperString_t *out, const char *str)
Creates a new String_t varible and populates the out varible with the content of str.
void * ViperStringDelete (ViperString_t *str)
Cleans up the String_t instead of manual deletion.
char * ViperFindNextChar (char *data)
This function searches for the next valid charter and not space, tabs and so on.
char * ViperFindNonNumeric (char *buffer)
char * ViperSkipLine (char *buffer)
Function Documentation
ViperFindNextChar()
char * ViperFindNextChar (char * data) [extern]
This function searches for the next valid charter and not space, tabs and so on.
Parameters
data :: the acctual data pointer.
Returns
either returns the passed in pointer \ , EOF or the next valid string/charter, if \ the passed in pointer is NULL then NULL will \ be returned.
Definition at line 65 of file stringer.c.
Referenced by ViperImageDecodePPM6().
ViperFindNonNumeric()
char * ViperFindNonNumeric (char * buffer) [extern]
Definition at line 82 of file stringer.c.
Referenced by ViperAtoi().
ViperSkipLine()
char * ViperSkipLine (char * buffer) [extern]
Definition at line 87 of file stringer.c.
Referenced by ViperImageDecodePPM6().
ViperStringCreate()
int64_t ViperStringCreate (ViperString_t * out, const char * str) [extern]
Creates a new String_t varible and populates the out varible with the content of str.
Parameters
out :: the out put file
str :: a c-string that will be copied into the String_t
Returns
Returns either the length of the new string or -1 on error
Definition at line 13 of file stringer.c.
References ViperString_t::bytes, ViperString_t::data, ViperString_t::sType, VIPER_STRUCTURE_TYPE_STRING, and ViperLogError.
Referenced by ViperApplicationCreate(), and ViperCreate().
ViperStringDelete()
void * ViperStringDelete (ViperString_t * str) [extern]
Cleans up the String_t instead of manual deletion.
Parameters
str :: The string to delete
Definition at line 42 of file stringer.c.
References ViperString_t::data.
Referenced by ViperDelete().