tests/utils/integer.c File Reference
#include "viper/debug/exceptions.h"
#include "viper/types/tests.h"
#include <stdio.h>
#include <limits.h>
#include <viper/utils/integer.h>
#include <viper/debug/logger.h>
#include <viper/io/printer.h>
Functions
void ExecuteItoaCrashTest (ViperTestInfo_t *info, int64_t value)
void ExecuteItoaCompersionTest (ViperTestInfo_t *info, char const *str, int64_t value)
void ExecuteItoaAtoiTest (ViperTestInfo_t *info, int64_t min, int64_t max)
void ExecuteItoaTest (ViperTestInfo_t *info)
This function is used to test all the integer functions and insure the quality is up to spec.
Function Documentation
ExecuteItoaAtoiTest()
void ExecuteItoaAtoiTest (ViperTestInfo_t * info, int64_t min, int64_t max)
Definition at line 41 of file integer.c.
References ViperTestInfo_t::testFailed, ViperTestInfo_t::testTotal, ViperAtoi(), ViperCatch, ViperItoa(), ViperPrintF(), ViperThrow, and ViperTry.
Referenced by ExecuteItoaTest().
ExecuteItoaCompersionTest()
void ExecuteItoaCompersionTest (ViperTestInfo_t * info, char const * str, int64_t value)
Definition at line 23 of file integer.c.
References ViperTestInfo_t::testFailed, ViperTestInfo_t::testTotal, ViperCatch, ViperItoa(), ViperPrintF(), ViperThrow, and ViperTry.
Referenced by ExecuteItoaTest().
ExecuteItoaCrashTest()
void ExecuteItoaCrashTest (ViperTestInfo_t * info, int64_t value)
Definition at line 10 of file integer.c.
References ViperTestInfo_t::testFailed, ViperTestInfo_t::testTotal, ViperCatch, ViperItoa(), ViperPrintF(), and ViperTry.
Referenced by ExecuteItoaTest().
ExecuteItoaTest()
void ExecuteItoaTest (ViperTestInfo_t * info)
This function is used to test all the integer functions and insure the quality is up to spec.
Definition at line 71 of file integer.c.
References ExecuteItoaAtoiTest(), ExecuteItoaCompersionTest(), and ExecuteItoaCrashTest().
Referenced by Main().