tests/math/log.c File Reference
#include <stdio.h>
#include <viper/debug/exceptions.h>
#include <viper/types/tests.h>
#include <viper/math/log.h>
#include <viper/debug/logger.h>
Functions
void ExecuteLogTest (ViperTestInfo_t *info, int excpeted, int value, int base)
void ExecuteLogTests (ViperTestInfo_t *info)
Function Documentation
ExecuteLogTest()
void ExecuteLogTest (ViperTestInfo_t * info, int excpeted, int value, int base)
Definition at line 8 of file log.c.
References ViperTestInfo_t::testFailed, ViperCatch, ViperLog(), ViperPrintF(), ViperThrow, and ViperTry.
Referenced by ExecuteLogTests().
ExecuteLogTests()
void ExecuteLogTests (ViperTestInfo_t * info)
Definition at line 22 of file log.c.
References ExecuteLogTest().
Referenced by Main().