include/viper_vulkan.h File Reference
#include "types.h"
#include "logger.h"
Functions
int VulkanInit (Application_t *app, Vulkan_t *vk)
Function Documentation
VulkanInit()
int VulkanInit (Application_t * app, Vulkan_t * vk) [extern]
Definition at line 238 of file viper_vulkan.c.
References String_t::data, Vulkan_t::dimensionsWindow, Vulkan_t::instance, LogError, __Application_t::name, STRUCTURE_TYPE_UNKOWN, STRUCTURE_TYPE_VULKAN, Vulkan_t::sType, Vulkan_t::surface, __Application_t::vulkan, VulkanCreateDevice(), VulkanCreateSwapchain(), VulkanGetPhysicalDevice(), VulkanInstanceCreate(), Vulkan_t::window, VectorInt2_t::x, and VectorInt2_t::y.
Referenced by ApplicationCreate().