source/viper_vulkan.c File Reference
#include "logger.h"
#include "types.h"
#include <GLFW/glfw3.h>
#include <viper_vulkan.h>
#include <vulkan/vulkan_core.h>
Functions
char ** VulkanGetExtensions (uint32_t *count, const char **extensions)
int VulkanInstanceCreate (Application_t *app, Vulkan_t *vk)
This function will create a VkInstance using the Vulkan_t->instance varible, allowing for smoth start of the application.
int VulkanGetPhysicalDevice (Application_t *app, Vulkan_t *vk)
int64_t VulkanCreateDevice (Application_t *app, Vulkan_t *vk)
int64_t VulkanCreateSwapchain (Application_t *app, Vulkan_t *vk)
int VulkanInit (Application_t *app, Vulkan_t *vk)
Variables
static const char * _ENGINE_NAME = "viper"
Hardcoding the name of the engine no reason to make it dymanic.
static const char * _INSTANCE_EXTENSIONS []
Additional dependencies for the instance.
static const char * _DEVICE_EXTENSIONS []
The needed devices extensions.
Function Documentation
VulkanCreateDevice()
int64_t VulkanCreateDevice (Application_t * app, Vulkan_t * vk)
Definition at line 152 of file viper_vulkan.c.
References _DEVICE_EXTENSIONS, Vulkan_t::device, LogDebug, LogError, and Vulkan_t::physicalDevice.
Referenced by VulkanInit().
VulkanCreateSwapchain()
int64_t VulkanCreateSwapchain (Application_t * app, Vulkan_t * vk)
Definition at line 215 of file viper_vulkan.c.
References Vulkan_t::device, LogDebug, Vulkan_t::surface, and Vulkan_t::swapchain.
Referenced by VulkanInit().
VulkanGetExtensions()
char ** VulkanGetExtensions (uint32_t * count, const char ** extensions)
Definition at line 27 of file viper_vulkan.c.
References LogDebug.
Referenced by VulkanInstanceCreate().
VulkanGetPhysicalDevice()
int VulkanGetPhysicalDevice (Application_t * app, Vulkan_t * vk)
We don't need to check for other devices if there is only one device
Definition at line 109 of file viper_vulkan.c.
References Vulkan_t::instance, LogDebug, LogError, and Vulkan_t::physicalDevice.
Referenced by VulkanInit().
VulkanInit()
int VulkanInit (Application_t * app, Vulkan_t * vk)
Definition at line 238 of file viper_vulkan.c.
References String_t::data, Vulkan_t::dimensionsWindow, Vulkan_t::instance, LogError, __Application_t::name, STRUCTURE_TYPE_UNKOWN, STRUCTURE_TYPE_VULKAN, Vulkan_t::sType, Vulkan_t::surface, __Application_t::vulkan, VulkanCreateDevice(), VulkanCreateSwapchain(), VulkanGetPhysicalDevice(), VulkanInstanceCreate(), Vulkan_t::window, VectorInt2_t::x, and VectorInt2_t::y.
Referenced by ApplicationCreate().
VulkanInstanceCreate()
int VulkanInstanceCreate (Application_t * app, Vulkan_t * vk)
This function will create a VkInstance using the Vulkan_t->instance varible, allowing for smoth start of the application.
If Application_t->name is set this will be used for the application name, as for the engine name its hard coded to Viper.
Definition at line 63 of file viper_vulkan.c.
References _ENGINE_NAME, _INSTANCE_EXTENSIONS, String_t::data, Vulkan_t::instance, LogDebug, LogError, __Application_t::name, and VulkanGetExtensions().
Referenced by VulkanInit().
Variable Documentation
_DEVICE_EXTENSIONS
const char* _DEVICE_EXTENSIONS[] [static]
Initial value:
= {
    VK_KHR_SWAPCHAIN_EXTENSION_NAME,
}
The needed devices extensions.
Definition at line 22 of file viper_vulkan.c.
Referenced by VulkanCreateDevice().
_ENGINE_NAME
const char* _ENGINE_NAME = "viper" [static]
Hardcoding the name of the engine no reason to make it dymanic.
Definition at line 11 of file viper_vulkan.c.
Referenced by VulkanInstanceCreate().
_INSTANCE_EXTENSIONS
const char* _INSTANCE_EXTENSIONS[] [static]
Initial value:
= {
}
Additional dependencies for the instance.
Definition at line 16 of file viper_vulkan.c.
Referenced by VulkanInstanceCreate().