source/vulkan/init.c File Reference
#include <viper/debug/logger.h>
#include <viper/types.h>
#include <viper/threading/master.h>
#include <GLFW/glfw3.h>
#include <viper/vulkan/init.h>
#include <vulkan/vulkan_core.h>
#include <viper/vulkan/instance.h>
Macros
#define DEFAULT_WINDOW_SIZE_X 1920
The default value for the window size in the x direction if no value is set.
#define DEFAULT_WINDOW_SIZE_Y 1080
The default value for the window size in the y direction if no value is set.
Functions
int ViperVulkanGetPhysicalDevice (ViperApplication_t *app, ViperVulkan_t *vk)
int64_t ViperVulkanCreateDevice (ViperApplication_t *app, ViperVulkan_t *vk)
Creates the graphics device that will be used by the application.
int64_t VulkanCreateSwapchain (ViperApplication_t *app, ViperVulkan_t *vk)
int ViperVulkanInit (ViperApplication_t *app, ViperVulkan_t *vk)
This function is used to setup a vulkan rendering enviroment and all the needed functionallity.
Variables
static const char * _DEVICE_EXTENSIONS []
The needed devices extensions.
Macro Definition Documentation
DEFAULT_WINDOW_SIZE_X
#define DEFAULT_WINDOW_SIZE_X 1920
The default value for the window size in the x direction if no value is set.
Definition at line 21 of file init.c.
DEFAULT_WINDOW_SIZE_Y
#define DEFAULT_WINDOW_SIZE_Y 1080
The default value for the window size in the y direction if no value is set.
Definition at line 26 of file init.c.
Function Documentation
ViperVulkanCreateDevice()
int64_t ViperVulkanCreateDevice (ViperApplication_t * app, ViperVulkan_t * vk)
Creates the graphics device that will be used by the application.
Definition at line 85 of file init.c.
References _DEVICE_EXTENSIONS, ViperVkPhysicalDevice_t::data, ViperVkDevice_t::data, ViperVulkan_t::device, ViperVulkan_t::physicalDevice, ViperVulkanSwapchainInfo_t::queueCount, ViperVulkanSwapchainInfo_t::queueFamilyIndex, ViperVulkan_t::swapchainInfo, ViperLogDebug, and ViperLogError.
Referenced by ViperVulkanInit().
ViperVulkanGetPhysicalDevice()
int ViperVulkanGetPhysicalDevice (ViperApplication_t * app, ViperVulkan_t * vk)
We don't need to check for other devices if there is only one device
Definition at line 28 of file init.c.
References ViperVkInstance_t::data, ViperVkPhysicalDevice_t::data, ViperVulkan_t::instance, ViperVulkan_t::physicalDevice, ViperLogDebug, ViperLogError, ViperUnsafeStructAccess, and ViperUnsafeStructRelease.
Referenced by ViperVulkanInit().
ViperVulkanInit()
int ViperVulkanInit (ViperApplication_t * app, ViperVulkan_t * vk)
This function is used to setup a vulkan rendering enviroment and all the needed functionallity.
Definition at line 194 of file init.c.
References ViperGLFWwindow_t::data, ViperString_t::data, ViperVkInstance_t::data, ViperVkSurfaceKHR_t::data, DEFAULT_WINDOW_SIZE_X, DEFAULT_WINDOW_SIZE_Y, ViperVulkan_t::dimensionsWindow, ViperVulkan_t::instance, __ViperApplication_t::name, ViperVulkan_t::sType, ViperVulkan_t::surface, VIPER_STRUCTURE_TYPE_UNKOWN, VIPER_STRUCTURE_TYPE_VULKAN, ViperLogError, ViperUnsafeStructAccess, ViperUnsafeStructRelease, ViperVulkanCreateDevice(), ViperVulkanGetPhysicalDevice(), ViperVulkanInstanceCreate(), __ViperApplication_t::vulkan, VulkanCreateSwapchain(), ViperVulkan_t::window, ViperVectorInt2_t::x, and ViperVectorInt2_t::y.
Referenced by ViperApplicationCreate().
VulkanCreateSwapchain()
int64_t VulkanCreateSwapchain (ViperApplication_t * app, ViperVulkan_t * vk)
Definition at line 153 of file init.c.
References ViperVkPhysicalDevice_t::data, ViperVkDevice_t::data, ViperVkSurfaceKHR_t::data, ViperVkSwapchainKHR_t::data, ViperVulkan_t::device, ViperVulkan_t::physicalDevice, ViperVulkanSwapchainInfo_t::queueCount, ViperVulkan_t::surface, ViperVulkan_t::swapchain, ViperVulkan_t::swapchainInfo, ViperLogDebug, and ViperLogError.
Referenced by ViperVulkanInit().
Variable Documentation
_DEVICE_EXTENSIONS
const char* _DEVICE_EXTENSIONS[] [static]
Initial value:
= {
    VK_KHR_SWAPCHAIN_EXTENSION_NAME,
}
The needed devices extensions.
Definition at line 13 of file init.c.
Referenced by ViperVulkanCreateDevice().