include/viper/vulkan/init.h File Reference
#include <viper/types.h>
#include <viper/debug/logger.h>
Functions
int ViperVulkanInit (ViperApplication_t *app, ViperVulkan_t *vk)
This function is used to setup a vulkan rendering enviroment and all the needed functionallity.
Function Documentation
ViperVulkanInit()
int ViperVulkanInit (ViperApplication_t * app, ViperVulkan_t * vk) [extern]
This function is used to setup a vulkan rendering enviroment and all the needed functionallity.
Definition at line 194 of file init.c.
References ViperGLFWwindow_t::data, ViperString_t::data, ViperVkInstance_t::data, ViperVkSurfaceKHR_t::data, DEFAULT_WINDOW_SIZE_X, DEFAULT_WINDOW_SIZE_Y, ViperVulkan_t::dimensionsWindow, ViperVulkan_t::instance, __ViperApplication_t::name, ViperVulkan_t::sType, ViperVulkan_t::surface, VIPER_STRUCTURE_TYPE_UNKOWN, VIPER_STRUCTURE_TYPE_VULKAN, ViperLogError, ViperUnsafeStructAccess, ViperUnsafeStructRelease, ViperVulkanCreateDevice(), ViperVulkanGetPhysicalDevice(), ViperVulkanInstanceCreate(), __ViperApplication_t::vulkan, VulkanCreateSwapchain(), ViperVulkan_t::window, ViperVectorInt2_t::x, and ViperVectorInt2_t::y.
Referenced by ViperApplicationCreate().