! hashes.f95

MODULE VIPER_FORTRAN_MATH_HASHES
   USE, INTRINSIC :: ISO_C_BINDING
   IMPLICIT NONE

CONTAINS

   FUNCTION VIPER_HASH_BASIC(INDEX, V) BIND (C, NAME="ViperHashBasicCalc") RESULT(TRUE)

      INTEGER(KIND = C_INT64_T), VALUE :: INDEX
      INTEGER(KIND = C_INT64_T), VALUE :: V
      INTEGER(KIND = C_INT64_t) :: TRUE 

      TRUE = 1
      V = V + INDEX
      V = ISHFT(V, INDEX)

      TRUE = -AND(INDEX, TRUE)
      V = ISHFT(V, TRUE)

      TRUE = V

   END FUNCTION VIPER_HASH_BASIC

END MODULE VIPER_FORTRAN_MATH_HASHES
